import mongoose from "mongoose";

// ─── Purchase Item (Child) ──────────────────────────────────────────────────
const purchaseItemSchema = new mongoose.Schema(
  {
    purchaseId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Purchase",
      required: true,
    },
    productName: {
      type: String,
      required: true,
      trim: true,
    },
    quantity: {
      type: Number,
      required: true,
      min: 1,
    },
    costPrice: {
      type: Number,
      required: true,
      min: 0,
    },
    sellingPrice: {
      type: Number,
      required: true,
      min: 0,
    },
    // total = quantity * costPrice (auto-computed in controller)
    total: {
      type: Number,
      required: true,
    },
    // Batch is generated by the backend: BATCH-YYYY-NNNN
    batchId: {
      type: String,
    },
    status: {
      type: String,
      enum: ["UNLINKED", "LINKED"],
      default: "UNLINKED",
    },
    allocations: [//why allocations used here
      {
        variantId: { type: mongoose.Schema.Types.ObjectId, required: true },
        quantity: { type: Number, required: true },
      }
    ],
  },
  { timestamps: true }
);

export default mongoose.model("PurchaseItem", purchaseItemSchema);
